/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.rf96.battleship;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

public class App {
  private final TextPlayer player1;
  private final TextPlayer player2;

  public App(TextPlayer p1, TextPlayer p2) {
    player1 = p1;
    player2 = p2;
  }

  public void doPlacementPhase() throws IOException {
    player1.doPlacementPhase();
    player2.doPlacementPhase();
  }

  /**
     This should let player1 play a turn, then
   see if player 2 has lost. Then let player 2 play a turn and see if player 1 has lost.
   It should repeat this until one player has lost, then report the outcome.
   */
  public void doAttackingPhase(Board<Character> b1,Board<Character> b2) throws IOException {
    BoardTextView p1View = new BoardTextView(b1);
    BoardTextView p2View = new BoardTextView(b2);
    while(true){
      player1.playOneTurn(b2,p2View,"Your Ocean", "Player " +player2.getName() + "'s Ocean" );
      if(b2.isLose()){
        System.out.println("Player "+ player1.getName() + " Win!");
        break;
      }
      player2.playOneTurn(b1,p1View,"Your Ocean", "Player " +player1.getName() + "'s Ocean" );
      if(b1.isLose()){
        System.out.println("Player "+ player2.getName() + " Win!");
        break;
      }
    }
  }


  public static void main(String[] args) throws IOException {

    Board<Character> b1 = new BattleShipBoard<Character>(10, 20,'X');
    Board<Character> b2 = new BattleShipBoard<Character>(10, 20,'X');
    BufferedReader input = new BufferedReader(new InputStreamReader(System.in));
    V1ShipFactory factory = new V1ShipFactory();
    TextPlayer p1 = new TextPlayer("A", b1, input, System.out, factory);
    TextPlayer p2 = new TextPlayer("B", b2, input, System.out, factory);

    App app = new App(p1, p2);
    app.doPlacementPhase();
    app.doAttackingPhase(b1, b2);

  }

}
